module.exports = {
  docs: [
    {
      type: 'category',
      label: 'Introduction',
      collapsed: true,
      items: ['introduction/getting-started', 'introduction/comparison', 'introduction/video-overview'],
    },
    {
      type: 'category',
      label: 'Concepts',
      collapsed: true,
      items: [
        'concepts/queries',
        'concepts/mutations',
        'concepts/error-handling',
        'concepts/conditional-fetching',
        'concepts/pagination',
        'concepts/polling',
        'concepts/prefetching',
        'concepts/optimistic-updates',
        'concepts/code-splitting',
        'concepts/code-generation',
        'concepts/customizing-create-api',
      ],
    },
    {
      type: 'category',
      label: 'API Reference',
      collapsed: true,
      items: [
        {
          type: 'category',
          label: 'Exports',
          collapsed: false,
          items: [
            'api/exports/createApi',
            'api/exports/fetchBaseQuery',
            'api/exports/ApiProvider',
            'api/exports/setupListeners',
          ],
        },
        {
          type: 'category',
          label: 'Api created by createApi',
          collapsed: false,
          items: [
            'api/created-api/overview',
            'api/created-api/injectEndpoints',
            'api/created-api/enhanceEndpoints',
            'api/created-api/internalActions',
            'api/created-api/redux-integration',
            {
              type: 'category',
              label: 'endpoints',
              collapsed: false,
              items: [
                'api/created-api/endpoints/overview',
                'api/created-api/endpoints/initiate',
                'api/created-api/endpoints/matchers',
                'api/created-api/endpoints/select',
              ],
            },
            {
              type: 'category',
              label: 'Hooks (React only)',
              collapsed: false,
              items: [
                'api/created-api/hooks/overview',
                'api/created-api/hooks/useQuerySubscription',
                'api/created-api/hooks/useMutation',
                'api/created-api/hooks/useQueryState',
                'api/created-api/hooks/useQuery',
              ],
            },
            {
              type: 'category',
              label: 'util',
              collapsed: false,
              items: [
                'api/created-api/util/updateQueryResult',
                'api/created-api/util/patchQueryResult',
                'api/created-api/util/prefetchThunk',
              ],
            },
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Examples',
      collapsed: true,
      items: [
        'examples/examples-overview',
        'examples/authentication',
        'examples/react-hooks',
        'examples/react-class-components',
        'examples/react-with-graphql',
        'examples/react-optimistic-updates',
        'examples/svelte',
      ],
    },
  ],
};
